### ISSUE TITLE
Proposed new format

### ISSUE THREAD

**Issue by mikeal** [mikeal/dag-json#11]
I’d like to have a new format for `dag-json` that was more optimized for performance. Instead of a being a single valid JSON object, I’d like to use a format more like this:

```
+——————————————————————— +
| int32 (end-of-overlay) |
+——————————————————————— +
| int32 (end-of-body)    | 
+——————————————————————— +
| overlay object         |
+——————————————————————— +
| body object            |
+——————————————————————— +
| Binary Data.           |
+——————————————————————— +
```

```javascript
// Overlay Object
{ path:
  { to:
    { link: cid.toBaseEncodedString
      binary: [startOffset, endOffset]
     }
  }
}
```

For a regular parse, you pull the first two integers and use them to slice the overlay and body objects out of the data. You then overwrite the data from the overlay with CID instances for links and binary type objects for the binary data parsed out of the end of the block using the offset information in the overlay.

This has several benefits.

* Binary data can stay in binary and not eat base encoding penalties.
* We would no longer reserve any special keys or namespaces in the object.
* When doing graph traversal you’d only have to parse out the overlay in order to find out of what you’re looking for is in a link. Storage engines could even index the offsets allowing for very fast traversal through blocks that also have a lot binary data.

Thoughts?

**Comment by vmx** [comment]
General comment: for me this reads like another binary format. I'm unsure if we need one, given we have CBOR already.

For the two offsets I would use the length of them instead, that sounds more common to me (and adding those to isn't such an expensive operation).

Can you give an example of the `body object`? I don't understand how the overlay is applied to it.

**Comment by mikeal** [comment]
The `body` object is all the data you want to encode that is only in basic JSON types. In most cases the majority of the data will be in the body, only links and binary are encoded in the overlay.

So, a JS object of

```javascript
{ foo: “bar”
   link: new CID(),
   bin: Buffer.from(‘asdf’)
}
```

Would be encoded as

```
// overlay
{ link: baseEncodedLink,
  bin: [93, 97]
}
// body
{ foo: “bar”}
```

The binary data would be appended to the end.

**Comment by vmx** [comment]
Thanks, I got it now. So the `body object` contains all the data that JSON natively supports, the `overlay` contains the data that is needed for the IPLD Data Model, but can't unambiguously encoded in JSON.

One problem with the overlay is arrays where the ordering matters. Example:

```JSON
```

**Comment by mikeal** [comment]
Hrm... I hadn’t entirely worked out how the arrays stuff would work. I’ll have to figure out a more complicated encoding scheme for that :(

**Comment by mikeal** [comment]
I’m closing this as I no longer think this is a good direction.

There’s a surprising number of services that accept native JSON and don’t support binary well (like all of AWS, surprisingly) so moving to a format that doesn’t encode into pure JSON is a non-starter.

It’s also incredibly nice to be able to do an HTTP PUT w/ the raw block as ‘application/json’ in a lot of different libraries.

In short, SHUT IT DOWN!
